/*
 * Base16: https://github.com/chriskempson/base16
 */

#define THEME_BACKGROUND "#FFFFFF"
#define THEME_FOREGROUND "#101010"

/*
 * Colors
 */
#define THEME_BLACK "#FFFFFF"
#define THEME_RED "#FF0086"
#define THEME_GREEN "#00C918"
#define THEME_YELLOW "#ABA800"
#define THEME_BLUE "#3777E6"
#define THEME_MAGENTA "#AD00A1"
#define THEME_CYAN "#1FAAAA"
#define THEME_WHITE "#101010"

/*
 * Bright colors
 */

#define THEME_BRIGHTBLACK "#B0B0B0"
#define THEME_BRIGHTRED "#FF0086"
#define THEME_BRIGHTGREEN "#00C918"
#define THEME_BRIGHTYELLOW "#ABA800"
#define THEME_BRIGHTBLUE "#3777E6"
#define THEME_BRIGHTMAGENTA "#AD00A1"
#define THEME_BRIGHTCYAN "#1FAAAA"
#define THEME_BRIGHTWHITE "#202020"
