/*
 * Base16: https://github.com/chriskempson/base16
 */

#define THEME_BACKGROUND "#1C1E26"
#define THEME_FOREGROUND "#CBCED0"

/*
 * Colors
 */
#define THEME_BLACK "#1C1E26"
#define THEME_RED "#E95678"
#define THEME_GREEN "#29D398"
#define THEME_YELLOW "#FAC29A"
#define THEME_BLUE "#26BBD9"
#define THEME_MAGENTA "#EE64AC"
#define THEME_CYAN "#59E1E3"
#define THEME_WHITE "#CBCED0"

/*
 * Bright colors
 */

#define THEME_BRIGHTBLACK "#6F6F70"
#define THEME_BRIGHTRED "#E95678"
#define THEME_BRIGHTGREEN "#29D398"
#define THEME_BRIGHTYELLOW "#FAC29A"
#define THEME_BRIGHTBLUE "#26BBD9"
#define THEME_BRIGHTMAGENTA "#EE64AC"
#define THEME_BRIGHTCYAN "#59E1E3"
#define THEME_BRIGHTWHITE "#E3E6EE"
