/*
 * Base16: https://github.com/chriskempson/base16
 */

#define THEME_BACKGROUND "#292D3E"
#define THEME_FOREGROUND "#959DCB"

/*
 * Colors
 */
#define THEME_BLACK "#292D3E"
#define THEME_RED "#F07178"
#define THEME_GREEN "#C3E88D"
#define THEME_YELLOW "#FFCB6B"
#define THEME_BLUE "#82AAFF"
#define THEME_MAGENTA "#C792EA"
#define THEME_CYAN "#89DDFF"
#define THEME_WHITE "#959DCB"

/*
 * Bright colors
 */

#define THEME_BRIGHTBLACK "#676E95"
#define THEME_BRIGHTRED "#F07178"
#define THEME_BRIGHTGREEN "#C3E88D"
#define THEME_BRIGHTYELLOW "#FFCB6B"
#define THEME_BRIGHTBLUE "#82AAFF"
#define THEME_BRIGHTMAGENTA "#C792EA"
#define THEME_BRIGHTCYAN "#89DDFF"
#define THEME_BRIGHTWHITE "#FFFFFF"
