/*
 * Base16: https://github.com/chriskempson/base16
 */

#define THEME_BACKGROUND "#3C4C55"
#define THEME_FOREGROUND "#C5D4DD"

/*
 * Colors
 */
#define THEME_BLACK "#3C4C55"
#define THEME_RED "#83AFE5"
#define THEME_GREEN "#7FC1CA"
#define THEME_YELLOW "#A8CE93"
#define THEME_BLUE "#83AFE5"
#define THEME_MAGENTA "#9A93E1"
#define THEME_CYAN "#F2C38F"
#define THEME_WHITE "#C5D4DD"

/*
 * Bright colors
 */

#define THEME_BRIGHTBLACK "#899BA6"
#define THEME_BRIGHTRED "#83AFE5"
#define THEME_BRIGHTGREEN "#7FC1CA"
#define THEME_BRIGHTYELLOW "#A8CE93"
#define THEME_BRIGHTBLUE "#83AFE5"
#define THEME_BRIGHTMAGENTA "#9A93E1"
#define THEME_BRIGHTCYAN "#F2C38F"
#define THEME_BRIGHTWHITE "#556873"
